export const categories = [
    {
        name: '#beach, #summer, #crops, #shorts',
        description: 'Summer Vibes ☀️🍹',
        imageSrc: require('../assets/img/azul.gif'),
        imageAlt: 'Summer Vibes ☀️🍹',
        href: '#',
    },
    {
        name: '#joggers, #hoodies, #nightsuit, #t-shirts ',
        description: 'Home Office 💻🏠',
        imageSrc: require('../assets/img/home.gif'),
        imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
        href: '#',
    },
    {
        name: '#bohemia, #dress, #shirts',
        description: '⭐ Rare beauty',
        imageSrc: require('../assets/img/rare.png'),
        imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
        href: '#',
    },
    {
        name: '#printed, #jeans, #dress, #shirts',
        description: 'The Bitch is Back ⚜️',
        imageSrc: require('../assets/img/the_bitch_is_back.gif'),
        imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        href: '#',
    },
    {
        name: '#jeans, #dress, #shirts, #cardigan,',
        description: 'Love in the air 🍽❤️‍🔥',
        imageSrc: require('../assets/img/cita.webp'),
        imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
        href: '#',
    },
    {
        name: '#jeans, #shorts, #dress, #shirts',
        description: "who's that Girl",
        imageSrc: require('../assets/img/who.webp'),
        imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
        href: '#',
    },
    {
        name: '#dress',
        description: 'Lady Million 🪙👛 ',
        imageSrc: require('../assets/img/elegant.webp'),
        imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        href: '#',
    },
    {
        name: '#bikini, #top',
        description: 'Hot confidence ⛱️🔞',
        imageSrc: require('../assets/img/sexy.webp'),
        imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
        href: '#',
    },
    {
        name: '#XXXXL, #XXXL, #XXL, #XL #L, #M, #S, ',
        description: 'Body Positive 💌🧁',
        imageSrc: require('../assets/img/fat.webp'),
        imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
        href: '#',
    },
]