export const categories = [
  {
    name: '#beach, #summer, #crops, #shorts',
    description: 'Summer Vibes ☀️🍹',
    imageSrc: require('../assets/img/azul.gif'),
    imageAlt: 'Summer Vibes ☀️🍹',
    href: '/offers',
  },
  {
    name: '#joggers, #hoodies, #nightsuit, #t-shirts ',
    description: 'Home Office 💻🏠',
    imageSrc: require('../assets/img/home.gif'),
    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
    href: '/offers',
  },
  {
    name: '#bohemia, #dress, #shirts',
    description: '⭐ Rare beauty',
    imageSrc: require('../assets/img/rare.png'),
    imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
    href: '/offers',
  },
  {
    name: '#printed, #jeans, #dress, #shirts',
    description: 'The Bitch is Back ⚜️',
    imageSrc: require('../assets/img/the_bitch_is_back.gif'),
    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
    href: '/offers',
  },
  {
    name: '#jeans, #dress, #shirts, #cardigan,',
    description: 'Love in the air 🍽❤️‍🔥',
    imageSrc: require('../assets/img/cita.webp'),
    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
    href: '/offers',
  },
  {
    name: '#jeans, #shorts, #dress, #shirts',
    description: "who's that Girl",
    imageSrc: require('../assets/img/who.webp'),
    imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
    href: '/offers',
  },
  {
    name: '#dress',
    description: 'Lady Million 🪙👛 ',
    imageSrc: require('../assets/img/elegant.webp'),
    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
    href: '/offers',
  },
  {
    name: '#bikini, #top',
    description: 'Hot confidence ⛱️🔞',
    imageSrc: require('../assets/img/sexy.webp'),
    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
    href: '/offers',
  },
  {
    name: '#XXXXL, #XXXL, #XXL, #XL #L, #M, #S, ',
    description: 'Body Positive 💌🧁',
    imageSrc: require('../assets/img/fat.webp'),
    imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
    href: '/offers',
  },
];

export const products = [
  {
    id: 1,
    name: 'Basic Tee',
    amount: 0,
    imageSrc: require('../assets/img/pijama.webp'),
    imageAlt: "Front of men's Basic Tee in black.",
    price: 8,
    color: 'Black',
  },
  {
    id: 2,
    name: 'Jeans',
    amount: 0,
    imageSrc: require('../assets/img/sport.webp'),
    imageAlt: "Front of men's Basic Tee in black.",
    price: 5,
    color: 'Black',
  },
  {
    id: 3,
    name: 'Shorts',
    amount: 0,
    imageSrc: require('../assets/img/sports.webp'),
    imageAlt: "Front of men's Basic Tee in black.",
    price: 3,
    color: 'Black',
  },
  {
    id: 4,
    name: 'Basic T-shirt',
    amount: 0,
    imageSrc: require('../assets/img/beige.webp'),
    imageAlt: "Front of men's Basic Tee in black.",
    price: 5,
    color: 'Black',
  },
  {
    id: 5,
    name: 'Dress',
    amount: 0,
    imageSrc: require('../assets/img/dress.webp'),
    imageAlt: "Front of men's Basic Tee in black.",
    price: 10,
    color: 'Black',
  },
  {
    id: 6,
    name: 'Cardigans',
    amount: 0,
    imageSrc: require('../assets/img/jeans.webp'),
    imageAlt: "Front of men's Basic Tee in black.",
    price: 7,
    color: 'Black',
  },
  {
    id: 7,
    name: 'Basic Jeans',
    amount: 0,
    imageSrc: require('../assets/img/skirts.webp'),
    imageAlt: "Front of men's Basic Tee in black.",
    price: 5,
    color: 'Black',
  },
  {
    id: 8,
    name: 'Basic Dress',
    amount: 0,
    imageSrc: require('../assets/img/dresses.webp'),
    imageAlt: "Front of men's Basic Tee in black.",
    price: 24,
    color: 'Black',
  }
]
